"""Initial schema: tickets, labels, ticket_labels

Revision ID: e0f1abcb761f
Revises: 
Create Date: 2025-12-04 16:06:25.104411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0f1abcb761f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建枚举类型（如果不存在）
    conn = op.get_bind()
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE ticketpriority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE ticketstatus AS ENUM ('OPEN', 'COMPLETED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    ticketpriority_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority')
    ticketstatus_enum = sa.Enum('OPEN', 'COMPLETED', name='ticketstatus')
    
    # 创建 labels 表
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=True)
    
    # 检查并处理旧表（如果存在）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    table_names = inspector.get_table_names()
    
    # 删除旧表（如果存在）
    if 'tags' in table_names:
        op.execute("DROP TABLE IF EXISTS ticket_tags CASCADE;")
        op.execute("DROP TABLE IF EXISTS tags CASCADE;")
    
    # 创建或修改 tickets 表
    if 'tickets' not in table_names:
        # 使用原始 SQL 创建表，避免 SQLAlchemy 尝试创建枚举类型
        op.execute("""
            CREATE TABLE tickets (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                title VARCHAR(200) NOT NULL,
                description TEXT,
                priority ticketpriority NOT NULL DEFAULT 'MEDIUM',
                status ticketstatus NOT NULL DEFAULT 'OPEN',
                completed_at TIMESTAMP WITH TIME ZONE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            );
        """)
    else:
        # 检查现有表结构，如果 id 列不是 UUID，需要重建表
        columns = {col['name']: col for col in inspector.get_columns('tickets')}
        needs_rebuild = False
        
        if 'id' in columns and str(columns['id']['type']) != 'UUID':
            needs_rebuild = True
        
        if needs_rebuild:
            # 删除旧表并重建（这是初始迁移，通常不会有重要数据）
            op.execute("DROP TABLE IF EXISTS ticket_tags CASCADE;")
            op.execute("DROP TABLE IF EXISTS tickets CASCADE;")
            # 使用原始 SQL 创建表，避免 SQLAlchemy 尝试创建枚举类型
            op.execute("""
                CREATE TABLE tickets (
                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                    title VARCHAR(200) NOT NULL,
                    description TEXT,
                    priority ticketpriority NOT NULL DEFAULT 'MEDIUM',
                    status ticketstatus NOT NULL DEFAULT 'OPEN',
                    completed_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
                );
            """)
        else:
            # 表结构正确，只需添加新列（如果不存在）
            if 'priority' not in columns:
                op.add_column('tickets', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority', create_type=False), nullable=False, server_default='MEDIUM'))
            if 'completed_at' not in columns:
                op.add_column('tickets', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    
    # 创建索引（如果不存在）
    # 重新获取 inspector，因为表可能已被重建
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = {idx['name']: idx for idx in inspector.get_indexes('tickets')}
    except Exception:
        indexes = {}
    
    if 'ix_tickets_priority' not in indexes:
        op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    if 'ix_tickets_status' not in indexes:
        op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    if 'ix_tickets_title' not in indexes:
        op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    
    # 创建 ticket_labels 关联表
    op.create_table('ticket_labels',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'label_id')
    )
    
    # 添加全文搜索索引
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_tickets_title_gin ON tickets 
        USING gin(to_tsvector('simple', title));
    """)
    
    # 添加模糊搜索索引
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_tickets_title_like ON tickets(title varchar_pattern_ops);
    """)
    
    # 创建 updated_at 触发器函数
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # 为 tickets 表创建触发器
    op.execute("""
        DROP TRIGGER IF EXISTS trg_tickets_update_updated_at ON tickets;
        CREATE TRIGGER trg_tickets_update_updated_at
        BEFORE UPDATE ON tickets
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    
    # 为 labels 表创建触发器
    op.execute("""
        DROP TRIGGER IF EXISTS trg_labels_update_updated_at ON labels;
        CREATE TRIGGER trg_labels_update_updated_at
        BEFORE UPDATE ON labels
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    
    # 创建 completed_at 触发器函数
    op.execute("""
        CREATE OR REPLACE FUNCTION set_completed_at_on_status_change()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.status = 'completed' AND (OLD.status IS NULL OR OLD.status != 'completed') THEN
                NEW.completed_at = CURRENT_TIMESTAMP;
            END IF;
            
            IF NEW.status = 'open' AND OLD.status = 'completed' THEN
                NEW.completed_at = NULL;
            END IF;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # 为 tickets 表创建状态触发器
    op.execute("""
        DROP TRIGGER IF EXISTS trg_tickets_set_completed_at ON tickets;
        CREATE TRIGGER trg_tickets_set_completed_at
        BEFORE UPDATE OF status ON tickets
        FOR EACH ROW
        EXECUTE FUNCTION set_completed_at_on_status_change();
    """)
    
    # 插入预设标签
    op.execute("""
        INSERT INTO labels (id, name, color, description) VALUES
        (gen_random_uuid(), 'Bug', '#ef4444', '需要修复的缺陷或错误'),
        (gen_random_uuid(), 'Feature', '#22c55e', '新功能开发'),
        (gen_random_uuid(), 'Enhancement', '#3b82f6', '现有功能改进'),
        (gen_random_uuid(), 'Documentation', '#8b5cf6', '文档相关任务'),
        (gen_random_uuid(), 'Question', '#f59e0b', '需要讨论或澄清的问题'),
        (gen_random_uuid(), 'Urgent', '#dc2626', '紧急任务')
        ON CONFLICT (name) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 清理触发器
    op.execute("DROP TRIGGER IF EXISTS trg_tickets_set_completed_at ON tickets;")
    op.execute("DROP TRIGGER IF EXISTS trg_tickets_update_updated_at ON tickets;")
    op.execute("DROP TRIGGER IF EXISTS trg_labels_update_updated_at ON labels;")
    
    # 清理函数
    op.execute("DROP FUNCTION IF EXISTS set_completed_at_on_status_change();")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
    
    # 删除索引
    op.execute("DROP INDEX IF EXISTS idx_tickets_title_gin;")
    op.execute("DROP INDEX IF EXISTS idx_tickets_title_like;")
    
    # 删除表
    op.drop_table('ticket_labels')
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    op.drop_table('labels')
    
    # 删除 tickets 表的索引和列
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    
    # 删除枚举类型
    sa.Enum(name='ticketstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ticketpriority').drop(op.get_bind(), checkfirst=True)
    
    # 删除列（如果存在）
    try:
        op.drop_column('tickets', 'completed_at')
        op.drop_column('tickets', 'priority')
    except Exception:
        pass
    
    # ### end Alembic commands ###


